import { Code2, Heart, Scale, Target } from 'lucide-react'
import { Button, Card, Container, IconBadge, PageHeader, SectionTitle, GithubIcon } from '../components/ui.jsx'
import { AUTHOR, AUTHOR_URL, ISSUES_URL, REPO_URL } from '../lib/site.js'
import { useT } from '../lib/i18n.jsx'

export default function About() {
  const t = useT()

  const stack = [
    ['Electron', t('App desktop, tray e aggiornamenti con electron-updater', 'Desktop app, tray and updates with electron-updater')],
    ['React', t('Interfaccia della finestra', 'Window interface')],
    ['Tailwind CSS', t('Tema chiaro e scuro', 'Light and dark theme')],
    ['Vite', t('Build della UI', 'UI build')],
    ['Git for Windows', t('Push del Client con Git Credential Manager', 'Client push with Git Credential Manager')],
    ['GitHub API', t('Download verificati e controllo dei commit', 'Verified downloads and commit checks')],
    ['SteamCMD', t('Installazione e aggiornamento del server dedicato', 'Dedicated server install and updates')],
    ['GitHub Actions', t('Build e pubblicazione delle release', 'Release build and publishing')],
  ]

  const values = [
    [Target, t('Zero file a mano', 'Zero files by hand'), t(
      'Tutto si imposta dalla finestra. Nessun JSON da modificare, nessuno script da lanciare.',
      'Everything is set up from the window. No JSON to edit, no scripts to run.',
    )],
    [Heart, t('Il server prima di tutto', 'The server comes first'), t(
      'Verifica prima di fermare, backup prima di sostituire, rollback se qualcosa non parte.',
      "Verify before stopping, back up before replacing, roll back if something won't start.",
    )],
    [Code2, t('Codice aperto', 'Open code'), t(
      'Ogni riga è su GitHub e ogni release è costruita da GitHub Actions, in modo trasparente.',
      'Every line is on GitHub and every release is built by GitHub Actions, in the open.',
    )],
    [Scale, t('Licenza MIT', 'MIT License'), t(
      'Usalo, modificalo, adattalo alla tua community. Gratis, per sempre.',
      'Use it, change it, adapt it to your community. Free, forever.',
    )],
  ]

  return (
    <>
      <PageHeader eyebrow="About" title={t('Nato per chi gestisce un server di trucker', 'Made for people who run a trucking server')}>
        {t(
          'ETS2 Package Sync nasce da un problema concreto: ogni volta che la mod list cambia, qualcuno deve copiare due file sul server dedicato e riavviarlo. Ogni volta.',
          'ETS2 Package Sync comes from a real problem: every time the mod list changes, someone has to copy two files to the dedicated server and restart it. Every single time.',
        )}
      </PageHeader>

      <section className="py-20">
        <Container className="grid gap-12 lg:grid-cols-2">
          <div>
            <SectionTitle eyebrow={t('La storia', 'The story')} title={t('Da script a app completa', 'From a script to a full app')} />
            <div className="mt-6 space-y-4 leading-relaxed text-slate-600 dark:text-slate-400">
              <p>
                {t(
                  <>Il server dedicato di Euro Truck Simulator 2 e American Truck Simulator legge la lista delle mod da <code className="font-mono">server_packages.sii</code> e <code className="font-mono">.dat</code>, che si generano solo dal gioco. Se chi gestisce le mod e la macchina del server non sono la stessa persona (o lo stesso PC), aggiornarli diventa un lavoro manuale e facile da sbagliare.</>,
                  <>The Euro Truck Simulator 2 and American Truck Simulator dedicated server reads its mod list from <code className="font-mono">server_packages.sii</code> and <code className="font-mono">.dat</code>, which can only be generated by the game. When whoever manages the mods and the server machine aren't the same person (or PC), updating them becomes manual, error-prone work.</>,
                )}
              </p>
              <p>
                {t(
                  'Il progetto è partito come un piccolo strumento per automatizzare quel passaggio con GitHub ed è cresciuto release dopo release: supporto ad ATS, più server per PC, polling senza porte aperte, SteamCMD integrato, editor della sessione, console in tempo reale, interfaccia in italiano e inglese.',
                  'The project started as a small tool to automate that step with GitHub and grew release after release: ATS support, multiple servers per PC, polling with no open ports, built-in SteamCMD, session editor, live console, English and Italian interface.',
                )}
              </p>
              <p>
                {t(
                  "L'obiettivo resta lo stesso: esporti in gioco e il server è pronto, senza toccare nient'altro.",
                  'The goal is still the same: export in game and the server is ready, without touching anything else.',
                )}
              </p>
            </div>
          </div>
          <div className="grid gap-5 sm:grid-cols-2">
            {values.map(([icon, title, text]) => (
              <Card key={title}>
                <IconBadge icon={icon} />
                <h3 className="mt-4 font-semibold text-slate-900 dark:text-white">{title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-slate-600 dark:text-slate-400">{text}</p>
              </Card>
            ))}
          </div>
        </Container>
      </section>

      <section className="bg-slate-50 py-20 dark:bg-slate-900/30">
        <Container>
          <SectionTitle center eyebrow={t('Tecnologie', 'Technology')} title={t('Con cosa è costruito', "What it's built with")} />
          <div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {stack.map(([name, what]) => (
              <div key={name} className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900">
                <p className="font-semibold text-slate-900 dark:text-white">{name}</p>
                <p className="mt-1 text-sm text-slate-500">{what}</p>
              </div>
            ))}
          </div>
        </Container>
      </section>

      <section className="py-20">
        <Container className="max-w-3xl text-center">
          <img src={`https://github.com/${AUTHOR}.png?size=160`} alt={AUTHOR} className="mx-auto h-20 w-20 rounded-full ring-4 ring-orange-500/20" />
          <h2 className="mt-5 text-2xl font-bold text-slate-900 dark:text-white">{t('Sviluppato da', 'Built by')} {AUTHOR}</h2>
          <p className="mt-3 text-slate-600 dark:text-slate-400">
            {t(
              "Hai un'idea, hai trovato un bug o vuoi contribuire? Le issue e le pull request sono benvenute.",
              'Got an idea, found a bug or want to contribute? Issues and pull requests are welcome.',
            )}
          </p>
          <div className="mt-8 flex flex-wrap justify-center gap-3">
            <Button href={REPO_URL}>
              <GithubIcon className="h-4 w-4" /> Repository
            </Button>
            <Button href={ISSUES_URL} variant="secondary">{t('Segnala un problema', 'Report an issue')}</Button>
            <Button href={AUTHOR_URL} variant="secondary">{t('Profilo GitHub', 'GitHub profile')}</Button>
          </div>
          <p className="mt-12 text-xs text-slate-500">
            {t(
              'Euro Truck Simulator 2 e American Truck Simulator sono marchi di SCS Software. Steam e SteamCMD sono marchi di Valve Corporation. Questo progetto non è affiliato né approvato da SCS Software o Valve.',
              'Euro Truck Simulator 2 and American Truck Simulator are trademarks of SCS Software. Steam and SteamCMD are trademarks of Valve Corporation. This project is not affiliated with or endorsed by SCS Software or Valve.',
            )}
          </p>
        </Container>
      </section>
    </>
  )
}
